### ISSUE TITLE
ModuleNotFoundError: No module named 'leapc_cffi._leapc_cffi'

### ISSUE THREAD

**Issue by wetoo-cando** [ultraleap/leapc-python-bindings#10]
I am on Windows 10.

```
>python examples/visualiser.py

Traceback (most recent call last):
  File "c:\users\rahul\documents\code\leapc-python-bindings\leapc-python-api\src\leap\__init__.py", line 74, in <module>
    from leapc_cffi import ffi, libleapc
  File "C:/Program Files/Ultraleap/LeapSDK\leapc_cffi\__init__.py", line 1, in <module>
    from ._leapc_cffi import ffi, lib as libleapc
ModuleNotFoundError: No module named 'leapc_cffi._leapc_cffi'
```

I tried the instructions in [the README](https://github.com/ultraleap/leapc-python-bindings/blob/main/README.md). However, when I run the step

`python -m build leapc-cffi`, I get a long list of linker errors (unresolved external symbols I am guessing belong to the LeapC library):

```
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapSetPrimaryDevice@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapInterpolateFrameFromTimeEx@36
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapTelemetryGetNow@0
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapGetDeviceList@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapRectilinearToPixelByIndex@20
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapInterpolateHeadPoseEx@20
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapCloseConnection@4
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapRecordingOpen@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapSetConnectionMetadata@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapPixelToRectilinearByIndexEx@24
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapDistortionCoeffsEx@16
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapScaleOffsetMatrixEx@16
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapGetTrackingMode@4
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapExtrinsicCameraMatrixEx@16
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapInterpolateEyePositions@16
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapRecordingRead@16
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapGetDeviceCameraCount@8
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapDeviceTransformAvailable@4
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapRecordingGetStatus@8
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapPixelToRectilinearByIndex@20
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapCameraMatrix@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapRectilinearToPixelByIndexEx@24
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapSubscribeEvents@8
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapCreateConnection@8
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapSetTrackingModeEx@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapCreateClockRebaser@4
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapGetDeviceTransform@8
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapGetTrackingModeEx@8
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapGetFrameSize@16
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapGetConnectionInfo@8
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapCameraMatrixByIndex@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapScaleOffsetMatrixByIndex@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapInterpolateHeadPose@16
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapCheckLicenseFlag@12
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapRecordingClose@4
_leapc_cffi.obj : error LNK2001: unresolved external symbol __imp__LeapExtrinsicCameraMatrixByIndexEx@16
...
```

What am I doing wrong?

**Comment by wetoo-cando** [comment]
I also see some references to win32 in the build process:

`creating build\temp.win32-cpython-38\Release\build\temp.win32-cpython-38\Release`

Note sure where this `build` directory is being created.

But under `C:\Program Files\Ultraleap\LeapSDK\leapc_cffi\build`, I have only `amd64` things:
![image](https://github.com/user-attachments/assets/7036bc68-3316-421f-9652-2fc024796f20)

**Comment by wetoo-cando** [comment]
Furthermore I see
` Creating library build\temp.win32-cpython-38\Release\build\temp.win32-cpython-38\Release\_leapc_cffi.lib and object build\temp.win32-cpython-38\Release\build\temp.win32-cpython-38\Release\_leapc_cffi.exp`

It seems I already have these artifacts for amd64 (which is my arch):
![image](https://github.com/user-attachments/assets/771d0229-69d3-451c-a198-78141f40e0b1)

Can I just use these existing ones somehow?

**Comment by wetoo-cando** [comment]
The problem was that I had 32-bit python installed by mistake, instead of 64-bit.
With 64-bit python, I was able to get the examples/visualiser.py working with the standard instructions from the README.
